---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: main
    jkube.io/git-url: git@github.com:kodtodya/fuse-7-openshift-examples.git
    app.openshift.io/vcs-uri: git@github.com:kodtodya/fuse-7-openshift-examples.git
    jkube.io/git-commit: e9b3697ea83105e4ca1d7969ab1553bf40f31b76
    jkube.io/git-branch: main
  labels:
    app: rest-component-example
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.kodtodya.practice
  name: rest-component-example
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: rest-component-example
    provider: jkube
    group: com.kodtodya.practice
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: main
        jkube.io/git-url: git@github.com:kodtodya/fuse-7-openshift-examples.git
        app.openshift.io/vcs-uri: git@github.com:kodtodya/fuse-7-openshift-examples.git
        jkube.io/git-commit: e9b3697ea83105e4ca1d7969ab1553bf40f31b76
        jkube.io/git-branch: main
      labels:
        app: rest-component-example
        provider: jkube
        version: 1.0.0-SNAPSHOT
        group: com.kodtodya.practice
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: rest-component-example:latest
        imagePullPolicy: IfNotPresent
        name: spring-boot
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: rest-component-example:latest
    type: ImageChange
